//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallIT.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class call
    {
        public int id { get; set; }
        public string machineName { get; set; }
        public string machineIP { get; set; }
        public string sendName { get; set; }
        public string sendTel { get; set; }
        public string sendText { get; set; }
        public Nullable<System.DateTime> sendDatetime { get; set; }
    }
}
