//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallIT.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class call_staff
    {
        public int id { get; set; }
        public Nullable<int> callId { get; set; }
        public Nullable<int> staffId { get; set; }
        public string createBy { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
    }
}
